"""Figures for Question 3.

All plotting functions consume the tidy tables generated by ``q3.py``.  The
module deliberately keeps plotting separate from optimization so that figures
can be regenerated without repeating SLSQP solves.
"""

from __future__ import annotations

from pathlib import Path

import matplotlib.pyplot as plt
import numpy as np
import pandas as pd


plt.rcParams.update({
    "font.sans-serif": ["Microsoft YaHei", "SimHei", "DejaVu Sans"],
    "axes.unicode_minus": False,
    "figure.dpi": 120,
    "savefig.dpi": 300,
})


def _save(fig: plt.Figure, path: Path) -> None:
    fig.tight_layout()
    fig.savefig(path, bbox_inches="tight")
    plt.close(fig)


def plot_budget_allocation(selected: pd.DataFrame, out: Path) -> Path:
    """Plot N, D, quality and cost shares over the three budgets."""
    d = selected.sort_values("budget_1e21")
    fig, axes = plt.subplots(1, 3, figsize=(13, 4.5))
    x = np.arange(len(d))
    ax = axes[0]
    width = 0.32
    ax.bar(x - width/2, d["N_params_B"], width, label="参数 N (B)")
    ax.bar(x + width/2, d["D_tokens_B"], width, label="数据 D (B tokens)")
    ax.set_xticks(x, [f"{v:g}" for v in d["budget_1e21"]])
    ax.set_xlabel("预算 C (10^21 FLOPs)")
    ax.set_title("预算下的资源配置")
    ax.set_yscale("log")
    ax.legend(fontsize=8)
    ax.grid(axis="y", alpha=.25)
    ax = axes[1]
    ax.plot(x, d["Q_target"], color="#b94d31", marker="o", lw=2)
    ax.set_xticks(x, [f"{v:g}" for v in d["budget_1e21"]])
    ax.set_xlabel("预算 C (10^21 FLOPs)")
    ax.set_ylim(0.5, 1.0)
    ax.set_ylabel("质量目标 Q")
    ax.set_title("质量目标：各预算均触及上界")
    ax.grid(axis="y", alpha=.25)
    ax = axes[2]
    shares = ["train_cost_share", "quality_cost_share", "attention_cost_share"]
    labels = ["训练", "质量", "注意力"]
    bottom = np.zeros(len(d))
    for col, label in zip(shares, labels):
        ax.bar(x, d[col], bottom=bottom, label=label)
        bottom += d[col].to_numpy()
    ax.set_xticks(x, [f"{v:g}" for v in d["budget_1e21"]])
    ax.set_xlabel("预算 C (10^21 FLOPs)")
    ax.set_ylim(0, 1.02)
    ax.set_ylabel("成本占比")
    ax.set_title("成本构成")
    ax.legend(fontsize=8)
    ax.grid(axis="y", alpha=.25)
    _save(fig, out / "fig_q3_budget_allocation.png")
    return out / "fig_q3_budget_allocation.png"


def plot_quality_cost(curve: pd.DataFrame, out: Path) -> Path:
    """Compare the normalized exponential, power and logarithmic costs."""
    fig, ax = plt.subplots(figsize=(7, 4.5))
    for col, label in [("g_relative_exponential", "指数型"),
                       ("g_relative_power", "幂函数型"),
                       ("g_relative_logarithmic", "对数渐进型")]:
        ax.plot(curve["Q"], curve[col], lw=2, label=label)
    ax.set_xlabel("质量 Q")
    ax.set_ylabel("归一化质量增量成本")
    ax.set_title("三类质量成本函数敏感性")
    ax.legend()
    ax.grid(alpha=.25)
    _save(fig, out / "fig_q3_quality_cost_sensitivity.png")
    return out / "fig_q3_quality_cost_sensitivity.png"


def plot_context_sensitivity(results: pd.DataFrame, out: Path) -> Path:
    """Show the effect of every C7-supported context length."""
    fig, axes = plt.subplots(1, 2, figsize=(12, 4.5))
    for fn, group in results.groupby("cost_function"):
        g = group.sort_values(["budget_1e21", "context_tokens"])
        for budget, b in g.groupby("budget_1e21"):
            axes[0].plot(b["context_tokens"], b["loss"], marker="o", label=f"{fn}, C={budget:g}")
            axes[1].plot(b["context_tokens"], b["attention_cost_share"], marker="o", label=f"{fn}, C={budget:g}")
    for ax in axes:
        ax.set_xscale("symlog", linthresh=2048)
        ax.grid(alpha=.25)
        ax.set_xlabel("上下文长度 Lctx")
    axes[0].set_ylabel("代理 Loss")
    axes[0].set_title("上下文长度对最优 Loss 的影响")
    axes[1].set_ylabel("注意力成本占比")
    axes[1].set_title("上下文长度对成本结构的影响")
    axes[0].legend(fontsize=7, ncol=2)
    _save(fig, out / "fig_q3_context_sensitivity.png")
    return out / "fig_q3_context_sensitivity.png"


def plot_structural_transfer(selected: pd.DataFrame, out: Path) -> Path:
    """Plot resource shares and quality across budgets to expose transfers."""
    d = selected.sort_values("budget_1e21")
    fig, ax = plt.subplots(figsize=(8, 4.5))
    for col, label in [("train_cost_share", "训练成本"),
                       ("quality_cost_share", "质量成本"),
                       ("attention_cost_share", "注意力成本")]:
        ax.plot(d["budget_1e21"], d[col], marker="o", lw=2, label=label)
    ax2 = ax.twinx()
    ax2.plot(d["budget_1e21"], d["Q_target"], color="black", ls="--", marker="s", label="Q")
    ax.set_xscale("symlog", linthresh=0.01)
    ax.set_xlabel("预算 C (10^21 FLOPs)")
    ax.set_ylabel("成本占比")
    ax2.set_ylabel("质量目标 Q")
    ax.set_title("预算变化下的结构性转移")
    ax.grid(alpha=.25)
    lines = ax.lines + ax2.lines
    ax.legend(lines, [l.get_label() for l in lines], fontsize=8, loc="best")
    _save(fig, out / "fig_q3_structural_transfer.png")
    return out / "fig_q3_structural_transfer.png"


def plot_mix(selected_mix: pd.DataFrame, p0: np.ndarray, domains: tuple[str, ...], out: Path) -> Path:
    """Plot baseline and selected domain compositions."""
    d = selected_mix.copy()
    pivot = d.pivot_table(index="domain", columns="budget_1e21", values="share", aggfunc="first")
    pivot = pivot.reindex(domains)
    fig, ax = plt.subplots(figsize=(10, 5.5))
    x = np.arange(len(domains))
    width = 0.18
    ax.bar(x - width * (len(pivot.columns) / 2), p0, width, label="基线 p0")
    for j, budget in enumerate(pivot.columns):
        ax.bar(x + width * (j + 1 - len(pivot.columns) / 2), pivot[budget].to_numpy(), width, label=f"C={budget:g}")
    ax.set_xticks(x, domains, rotation=65, ha="right")
    ax.set_ylabel("领域配比")
    ax.set_title("最优领域配比与基线配比")
    ax.legend(fontsize=8, ncol=2)
    ax.grid(axis="y", alpha=.25)
    _save(fig, out / "fig_q3_domain_mix.png")
    return out / "fig_q3_domain_mix.png"


def plot_pareto(selected: pd.DataFrame, out: Path) -> Path:
    """Plot budget against the optimized surrogate loss."""
    fig, ax = plt.subplots(figsize=(7, 4.5))
    for fn, g in selected.groupby("cost_function"):
        g = g.sort_values("budget_1e21")
        ax.plot(g["budget_1e21"], g["loss"], marker="o", lw=2, label=fn)
    ax.set_xscale("log")
    ax.set_xlabel("预算 C (10^21 FLOPs)")
    ax.set_ylabel("代理 Loss")
    ax.set_title("预算与最优代理 Loss")
    ax.grid(alpha=.25)
    ax.legend()
    _save(fig, out / "fig_q3_budget_loss_pareto.png")
    return out / "fig_q3_budget_loss_pareto.png"


def plot_attention_critical(context_values: tuple[int, ...], out: Path) -> Path:
    """Show the analytic critical context length relative to C7 support."""
    critical = 30000.0
    fig, ax = plt.subplots(figsize=(8, 3.8))
    ax.axvline(critical, color="crimson", ls="--", lw=2, label=f"临界值 {critical:g}")
    ax.scatter(context_values, np.ones(len(context_values)), s=70, color="navy", zorder=3, label="C7 支持值")
    for v in context_values:
        ax.text(v, 1.03, str(v), ha="center", fontsize=8)
    ax.set_xscale("log")
    ax.set_yticks([])
    ax.set_xlabel("上下文长度 Lctx")
    ax.set_title("注意力成本与训练成本相当的临界关系")
    ax.legend(fontsize=8)
    ax.grid(axis="x", alpha=.25)
    _save(fig, out / "fig_q3_attention_critical_context.png")
    return out / "fig_q3_attention_critical_context.png"


def plot_cost_scale_sensitivity(d: pd.DataFrame, out: Path) -> Path:
    """Show how a free quality-processing calibration changes Q and loss."""
    d = d.sort_values("quality_cost_scale")
    fig, axes = plt.subplots(1, 2, figsize=(10, 4))
    axes[0].plot(d.quality_cost_scale, d.Q_target, marker="o", color="#b94d31")
    axes[1].plot(d.quality_cost_scale, d.loss, marker="o", color="#245a72")
    for ax in axes:
        ax.set_xscale("log")
        ax.set_xlabel("质量成本校准系数")
        ax.grid(alpha=.25)
    axes[0].set_ylabel("最优 Q")
    axes[1].set_ylabel("最优代理 Loss")
    axes[0].set_title("质量目标对成本标定的响应")
    axes[1].set_title("代理 Loss 对成本标定的响应")
    _save(fig, out / "fig_q3_cost_scale_sensitivity.png")
    return out / "fig_q3_cost_scale_sensitivity.png"


def plot_source_comparison(d: pd.DataFrame, out: Path) -> Path:
    """Compare complete B6--B8 and B1 coefficient conventions."""
    fig, axes = plt.subplots(1, 2, figsize=(11, 4.2))
    for source, g in d.groupby("coefficient_source"):
        g = g.sort_values("budget_1e21")
        label = "B6-B8 原生质量口径" if source == "b6_b8_lambda10" else "Pythia 经典项 + B6-B8 质量项（混合）"
        axes[0].plot(g.budget_1e21, g.N_params_B, marker="o", label=label)
        axes[1].plot(g.budget_1e21, g.D_tokens_B, marker="o", label=label)
    for ax, title, ylabel in zip(axes, ["两套系数口径的参数配置", "两套系数口径的数据配置"], ["N (B)", "D (B tokens)"]):
        ax.set_xscale("symlog", linthresh=.01); ax.set_yscale("log")
        ax.set_xlabel("预算 C (10^21 FLOPs)"); ax.set_ylabel(ylabel); ax.set_title(title); ax.grid(alpha=.25); ax.legend(fontsize=8)
    _save(fig, out / "fig_q3_coefficient_source_comparison.png")
    return out / "fig_q3_coefficient_source_comparison.png"


def plot_mix_sensitivity(d: pd.DataFrame, out: Path) -> Path:
    """Plot the response of the largest composition shifts to mix weights."""
    fig, ax = plt.subplots(figsize=(8, 4.5))
    for domain, g in d.groupby("domain"):
        g = g.sort_values("mix_effect_scale")
        ax.plot(g.mix_effect_scale, g.share_multiple, marker="o", label=domain)
    ax.set_xscale("log"); ax.set_xlabel("一阶替代项系数"); ax.set_ylabel("最优配比 / p0"); ax.set_title("配比主项 ±5 倍敏感性")
    ax.grid(alpha=.25); ax.legend(fontsize=7, ncol=2)
    _save(fig, out / "fig_q3_mix_sensitivity.png")
    return out / "fig_q3_mix_sensitivity.png"


def plot_eta_sensitivity(d: pd.DataFrame, out: Path) -> Path:
    """Plot eta and its analytic critical context length."""
    fig, ax = plt.subplots(figsize=(7, 4.2))
    ax.plot(d.eta, d.critical_context_tokens, marker="o", color="#245a72")
    ax.set_xscale("log"); ax.set_yscale("log"); ax.set_xlabel("注意力系数 η"); ax.set_ylabel("Lctx 临界值")
    ax.set_title("注意力系数敏感性：Lctx^crit=6/η"); ax.grid(alpha=.25)
    _save(fig, out / "fig_q3_eta_sensitivity.png")
    return out / "fig_q3_eta_sensitivity.png"
